/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jayanthaservicecenter;
import DBconnection.DB;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import com.itextpdf.text.*;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.print.*;

/**
 *
 * @author Ravindu
 */
public class Sales extends javax.swing.JFrame {
        DefaultListModel sparecart;
        DefaultListModel lubricantcart;
        String Brand;
        
        public static final String imgSrc = "src/Images/Untitled-2.png";
        
    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        
        sparecart = new DefaultListModel();
        lubricantcart = new DefaultListModel();
        
        String Brand = jComboBox2.getSelectedItem().toString();
        String model = jComboBox3.getSelectedItem().toString();
       
         jPanel4.setBackground(new Color(0,0,0,170));
         jPanel2.setBackground(new Color(0,0,0,170));
         jPanel7.setBackground(new Color(0,0,0,170));
        
        jTextField2.setBackground(new Color(0,0,0,200));
        jTextField5.setBackground(new Color(0,0,0,200));
        jTextField6.setBackground(new Color(0,0,0,200));
        jTextField7.setBackground(new Color(0,0,0,200));
        jTextField8.setBackground(new Color(0,0,0,200));
        jTextField9.setBackground(new Color(0,0,0,200));
        
        jButton1.setBackground(new Color(0,0,0,64));
        jButton10.setBackground(new Color(0,0,0,64));
        jButton11.setBackground(new Color(0,0,0,64));
        jButton12.setBackground(new Color(0,0,0,64));
        jButton3.setBackground(new Color(0,0,0,64));
        jButton4.setBackground(new Color(0,0,0,64));
        jButton5.setBackground(new Color(0,0,0,64));
        jButton6.setBackground(new Color(0,0,0,64));
       
              
        
        
        try{
            Connection c = DB.mycon();
            Statement s = c.createStatement();
            
            /*ResultSet rs = s.executeQuery("SELECT distinct ItemName FROM subpartname");
            while(rs.next()){
                jComboBox1.addItem(rs.getString("ItemName"));
            }*/
            ResultSet rs1 = s.executeQuery("SELECT * FROM brand");
            while(rs1.next()){
                jComboBox2.addItem(rs1.getString("Brand"));
            }
           // String Brand = jComboBox2.getSelectedItem().toString();
            //System.out.println(Brand);
            //ResultSet rs2 = s.executeQuery("SELECT  Model FROM vehicletype where Brand = '"+Brand+"' ");
            
            ResultSet rs2 = s.executeQuery("SELECT  Model FROM vehicletype  ");
                while(rs2.next()){
                jComboBox3.addItem(rs2.getString("Model"));
                }
                
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SALES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Find Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Brand");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Model");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("Sapre Parts");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("Lubricants");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Liters");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "5", "10" }));
        jComboBox4.setMaximumSize(new java.awt.Dimension(69, 23));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 156, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, 0, 156, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, 310));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Bill Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setOpaque(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 380, 460));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Search Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel6.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item No", "Ietm Name", "Quantity", "Selling Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 400, 180));

        jPanel12.setOpaque(false);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/48home.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout 1.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/48exit.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 330, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Item Name");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Price");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Quantity");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField6MouseReleased(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(158, 158, 158)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 520, 180));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Create Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(204, 204, 204));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNo", "ItemName", "Units", "Cost", "TotalCost"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Cost");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 204, 204));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Rs");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Discount");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(204, 204, 204));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Rs");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Total");

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(204, 204, 204));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Rs");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Calculate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("Save & Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7)
                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(jButton5)
                        .addComponent(jButton6)))
                .addGap(34, 34, 34))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 520, -1));

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(350, 220));
        dateChooserCombo2.setFormat(0);
        dateChooserCombo2.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        jPanel1.add(dateChooserCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Service Wall.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -10, 1460, 760));

        jTabbedPane1.addTab("Spare Parts/lubricants", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1350, 740));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Spare Parts");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Service Wall.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, -160, 2200, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // search
        
        String size = jComboBox4.getSelectedItem().toString();
        String ModelID = null;
        if(!(jComboBox1.getSelectedItem() == "Select") ||  !(jComboBox2.getSelectedItem() == "Select") || !(jComboBox3.getSelectedItem() == "Select")  || !(jComboBox4.getSelectedItem() == "Select")){
            try {
                if(jRadioButton1.isSelected()){
                   //jTextField15.setVisible(false);
                Connection c = DB.mycon();
                Statement s = c.createStatement();
               
                ResultSet rs = s.executeQuery("SELECT ItemID, ItemName,Quanty,Cost FROM subpartname WHERE ItemName ='" + jComboBox1.getSelectedItem().toString() + "'");
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //SimpleDateFormat DDate = new SimpleDateFormat("yyyy-MM-dd");
                //select model ID from the vehicle type        
                ResultSet rs1 = s.executeQuery("Select ModelID from vehicletype where Brand = '"+jComboBox2.getSelectedItem().toString()+"' and Model = '"+jComboBox3.getSelectedItem()+"'");
                while(rs1.next()){
                    ModelID = rs1.getString("modelID");
                }
                
                ResultSet rs3 = s.executeQuery("SELECT ItemID, ItemName,Quanty,Cost FROM subpartname WHERE ItemName ='" + jComboBox1.getSelectedItem().toString() + "' and ModelID = '"+ModelID+"'");
                jTable1.setModel(DbUtils.resultSetToTableModel(rs3));
            
                }
                else if(jRadioButton2.isSelected()){
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery("SELECT ItemName,Brand,Amount_L,Quantity,Price FROM lubricants WHERE ItemName ='" + jComboBox1.getSelectedItem().toString() + "'");
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));   
               }
                else{
                   JOptionPane.showMessageDialog(rootPane, "Select One"); 
                }
            } catch (Exception e) {
              //  e.printStackTrace();
            }
        }
        else if(!(jComboBox1.getSelectedItem() == "Select") && ( (jComboBox2.getSelectedItem() == "Select") || (jComboBox3.getSelectedItem() == "Select")|| (jComboBox4.getSelectedItem() == "Select"))){
            if(jRadioButton1.isSelected()){
                try{
                    Connection c = DB.mycon();
                    Statement s = c.createStatement();
               
                    ResultSet rs = s.executeQuery("SELECT * FROM subpartname WHERE ItemName ='" +  jComboBox1.getSelectedItem().toString() + "'");
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                catch(Exception e){
                    //e.printStackTrace();
                }
            }
        }
        else{
             JOptionPane.showMessageDialog(rootPane, "Fill One of the Fileds");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // selected Items
        Double dPrice =0.00 ;
        //double profitMargin = 500.00;
        int row = jTable1.getSelectedRow();
        String ItemNo = jTable1.getValueAt(row,1).toString();
        sparecart.addElement(ItemNo);
        //jList1.setModel(sparecart);
        jTextField2.setText(ItemNo);
        if(jRadioButton1.isSelected()){
            String Price = jTable1.getValueAt(row,3).toString();
            dPrice = Double.parseDouble(Price);
        }
        else if(jRadioButton2.isSelected()){
            String Price = jTable1.getValueAt(row,4).toString();
            dPrice = Double.parseDouble(Price);
        }
        //double SellPrice = dPrice + profitMargin;
        String sprice = Double.toString(dPrice);
        jTextField5.setText(sprice);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jComboBox4.setVisible(false);
        jLabel23.setVisible(false);
        jComboBox2.setVisible(true);
        jComboBox3.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        try{
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery("SELECT ItemID, ItemName,Quanty,SellingPrice FROM subpartname");
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
                jComboBox1.removeAllItems();
                ResultSet rs1 = s.executeQuery("SELECT distinct ItemName FROM subpartname");
                while(rs1.next()){
                jComboBox1.addItem(rs1.getString("ItemName"));
                }
                }
                catch(Exception e){
                   // e.printStackTrace();
                }
       // jComboBox1.removeAllItems();
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
            jComboBox4.setVisible(true);
            jComboBox2.setVisible(false);
            jComboBox3.setVisible(false);
            jLabel23.setVisible(true);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
        try{
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs = s.executeQuery("SELECT ItemNo, ItemName, Amount_L ,Quantity,SellingPrice FROM lubricants ");
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
                jComboBox1.removeAllItems();
                 ResultSet rs1 = s.executeQuery("SELECT distinct ItemName FROM lubricants");
                while(rs1.next()){
                jComboBox1.addItem(rs1.getString("ItemName"));
            }
        }
        catch(Exception e){
          //  e.printStackTrace();
        }
         //jComboBox1.removeAllItems();
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Remove Selected
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Add to purchase
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dateChooserCombo2.setDateFormat(sdf);
        
        if(!jTextField2.getText().isEmpty()|| !jTextField6.getText().isEmpty()|| !jTextField5.getText().isEmpty()){
            try{
            double itemcost = Double.parseDouble(jTextField5.getText());
            double qty = Double.parseDouble(jTextField6.getText());
            double cost = itemcost*qty; 
            String costS = Double.toString(cost);
            int row = jTable1.getSelectedRow();
            String ItemNo = jTable1.getValueAt(row, 0).toString();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            model.addRow(new Object[] {ItemNo, jTextField2.getText(),jTextField6.getText(),jTextField5.getText(), costS});
      
            
            if(jRadioButton1.isSelected()){
                String mqty = null;
                String dqty = null;
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs1 = s.executeQuery("select moveditems from subpartname where ItemID = '" + ItemNo + "' ");
                while(rs1.next()){
                    mqty = rs1.getString("moveditems");
                }
                    double dmqty = Double.parseDouble(mqty);
                    dmqty = dmqty + qty;
                    String updmqty = Double.toString(dmqty);
                    
                s.executeUpdate("UPDATE subpartname SET moveditems = '" + dmqty + "' where ItemID = '" + ItemNo + "' ");
                //JOptionPane.showMessageDialog(rootPane, "record has been Updated successfully ");
                
                ResultSet rs = s.executeQuery("select Quanty from subpartname where ItemID = '" + ItemNo + "' ");
                while(rs.next()){
                    dqty = rs.getString("Quanty");
                }
                    //System.out.println(dqty);
                double upQty = Double.parseDouble(dqty) - qty;
                String dupQty = Double.toString(upQty);
                
                s.executeUpdate("UPDATE subpartname SET Quanty = '" + dupQty + "' where ItemID = '" + ItemNo + "' ");
                s.executeUpdate("Insert into salesspare (ItemNo,ItemName,Date,Units,UnitPrice, 	TotalCost) values ('"+ItemNo +"','"+jTextField2.getText()+"','"+dateChooserCombo2.getText()+"','"+jTextField6.getText()+"','"+jTextField5.getText()+"','"+costS+"')");
                
                }
            if(jRadioButton2.isSelected()){
                
                String amnt = jTable1.getValueAt(row, 2).toString();
                String mqty = null;
                String dqty = null;
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs1 = s.executeQuery("select MovedStock from lubricants where ItemNo = '" + ItemNo + "' ");
                while(rs1.next()){
                    mqty = rs1.getString("MovedStock");
                }
                    double dmqty = Double.parseDouble(mqty);
                    dmqty = dmqty + qty;
                    String updmqty = Double.toString(dmqty);
                    
                s.executeUpdate("UPDATE lubricants SET MovedStock = '" + dmqty + "' where ItemNo = '" + ItemNo + "' ");
                //JOptionPane.showMessageDialog(rootPane, "record has been Updated successfully ");
                
                ResultSet rs = s.executeQuery("select Quantity from lubricants where ItemNo = '" + ItemNo + "' ");
                while(rs.next()){
                    dqty = rs.getString("Quantity");
                }
                    //System.out.println(dqty);
                double upQty = Double.parseDouble(dqty) - qty;
                String dupQty = Double.toString(upQty);
                
                s.executeUpdate("UPDATE lubricants SET Quantity = '" + dupQty + "' where ItemNo = '" + ItemNo + "' ");
                s.executeUpdate("Insert into salesslub (ItemNo,ItemName,Date,Amount_L,Units,UnitPrice,Total) values ('"+ItemNo +"','"+jTextField2.getText()+"','"+dateChooserCombo2.getText()+"','"+amnt+"','"+jTextField6.getText()+"','"+jTextField5.getText()+"','"+costS+"')");
                }
            }
                catch(Exception e){
                    //e.printStackTrace();
                }
                
            jTextField2.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Add relavant Field");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Cost
        double sum = 0.00;
        for(int i = 0; i < jTable2.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable2.getValueAt(i,4 ).toString());
        }
            String  cost = Double.toString(sum);
            jTextField7.setText(cost);
        if(jTextField8.getText().isEmpty()){
           jTextField9.setText(cost);
       }
        else{
            Double discount = Double.parseDouble(jTextField8.getText());
            Double Total = sum - discount;
            jTextField9.setText(Double.toString(Total));
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseReleased
/*        // TODO add your handling code here:
        String qty = jTextField6.getText();
        double dqty = Double.parseDouble(qty);
        String dbqty = null;
        int row = jTable1.getSelectedRow();
        String ItemNo = jTable1.getValueAt(row, 0).toString();
        try{
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                if(jRadioButton1.isSelected()){
                ResultSet rs = s.executeQuery("select Quanty from subpartname where ItemID =  '"+ItemNo+"'");
                while(rs.next()){
                    
                    dbqty = rs.getString("Quanty");
                }
                double dbsqty = Double.parseDouble(dbqty);
             if(dqty > dbsqty){
                 JOptionPane.showMessageDialog(rootPane, "No relavant Amount to purchase");
                  jTextField2.setText("");
                  jTextField5.setText("");
                  jTextField6.setText("");
             }
        }
                else if(jRadioButton2.isSelected()){
                ResultSet rs = s.executeQuery("select Quantity from lubricants where ItemNo =  '"+ItemNo+"'");
                while(rs.next()){
                    
                    dbqty = rs.getString("Quantity");
                }
                double dbsqty = Double.parseDouble(dbqty);
             if(dqty > dbsqty){
                 JOptionPane.showMessageDialog(rootPane, "No relavant Amount to purchase");
                  jTextField2.setText("");
                  jTextField5.setText("");
                  jTextField6.setText("");
                 
             }
        }
        }
        catch(Exception e){
            //e.printStackTrace();
        }*/
    }//GEN-LAST:event_jTextField6MouseReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // CreateBill
        
       jTextArea2.append("                             YOUR BILL                   " + '\n');
            jTextArea2.append('\n' +"                                                   " +  '\n'); 
            jTextArea2.append('\n' +"                                                   " +  '\n'); 

                   
            jTextArea2.append('\n' + "          Date   :       " + dateChooserCombo2.getText() + '\n');
            //jTextArea2.append('\n' + "        Item Name  :       " + jTextField32.getText() + '\n');
            //jTextArea2.append('\n' + "        Item Code  :       " + jTextField34.getText() + '\n'); 
            //jTextArea2.append('\n' + "       Buyer Name :       " + jTextField38.getText() + '\n'); 
            //jTextArea2.append('\n' + "        Quantity   :       " + jTextField35.getText()  + '\n');
            jTextArea2.append('\n' +"           Amount     :       " + jTextField7.getText() + '\n');
            jTextArea2.append('\n' +"           Discount   :       " + jTextField8.getText()+   '\n');
            jTextArea2.append('\n' +"           Net Amount :       " + jTextField9.getText() +   '\n');
            jTextArea2.append('\n' +"                                                      " +    '\n');
            jTextArea2.append('\n' +"                                          " +  '\n');
            jTextArea2.append('\n' +"          THANKYOU FOR PURCHASING         " +  '\n');
            jTextArea2.append('\n' +"          Jayantha Service Center                      " +  '\n');
            jTextArea2.append('\n' +"                Sooriyawewa                    " +  '\n');
            jTextArea2.append('\n' +"                                          " +  '\n');
            jTextArea2.append('\n' +"                  " +  '\n'); 
            jTextArea2.append('\n' +"        " +  '\n');  
     
         String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
   
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Sales "+dateChooserCombo2.getText()+".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult==JFileChooser.APPROVE_OPTION){
        String filePath = dialog.getSelectedFile().getPath();
        Document document = new Document(PageSize.A4, 50, 50, 140, 140);
        
        //Creation of PdfWriter object
        try {
            
            PdfWriter writer = PdfWriter.getInstance(document,
            new FileOutputStream(filePath));
            document.open();
            writer.setPageEvent(new MyPdfPageEventHelper("Service2.png"));
        } catch (Exception e) {
            System.out.println(e);
        }

        
       
          
            try {
                
            Paragraph title1 = new Paragraph("Invoice", 
            FontFactory.getFont(FontFactory.TIMES_ROMAN, 
            20, Font.BOLDITALIC, new CMYKColor(75, 68, 67,90)));
            Chapter chapter1 = new Chapter(title1, 1);
            Paragraph title5 = new Paragraph("Issued Date : "+today, 
            FontFactory.getFont(FontFactory.TIMES_ROMAN, 
            12, Font.NORMAL, new CMYKColor(75, 68, 67,90)));
            
            Paragraph title2 = new Paragraph("Bill Details", 
            FontFactory.getFont(FontFactory.TIMES_ROMAN, 
            14, Font.BOLDITALIC, new CMYKColor(75, 68, 67,90)));
            
            Paragraph title3 = new Paragraph("Invoice No : .........", 
            FontFactory.getFont(FontFactory.TIMES_ROMAN, 
            14, Font.BOLDITALIC, new CMYKColor(75, 68, 67,90)));
        
            title5.setAlignment(Element.ALIGN_RIGHT);
            document.add(title5);
            
            title1.setAlignment(Element.ALIGN_CENTER);
            document.add(title1);
            document.add(Chunk.NEWLINE);
            
            title2.setAlignment(Element.ALIGN_CENTER );
            document.add(title2);
            
            
            title3.setAlignment(Element.ALIGN_LEFT );
            document.add(title3);
            
            
            PdfPTable t = new PdfPTable(5); 
            t.setSpacingBefore(25);
            t.setSpacingAfter(25);
            
            t.addCell("ItemNo");
            t.addCell("Item Name");
            t.addCell("Units");
            t.addCell("Cost");
            t.addCell("Total Cost");
            
            for(int i = 0; i < jTable2.getRowCount(); i++ ){
                String ItemNo = jTable2.getValueAt(i, 0).toString();
                String ItemName = jTable2.getValueAt(i, 1).toString();
                String Units = jTable2.getValueAt(i, 2).toString();
                String Cost = jTable2.getValueAt(i, 3).toString();
                String tCost = jTable2.getValueAt(i, 4).toString();
                
                t.addCell(ItemNo);
                t.addCell(ItemName);
                t.addCell(Units);
                t.addCell(Cost);
                t.addCell(tCost);
            }
            
        document.add(t);
      
          Paragraph title6 = new Paragraph("Amount     :" + jTextField7.getText()+" Rs", 
          FontFactory.getFont(FontFactory.TIMES_ROMAN, 
          14, Font.NORMAL, new CMYKColor(75, 68, 67,90))); 
        
          Paragraph title7 = new Paragraph("Discount   :" + jTextField8.getText()+" Rs", 
          FontFactory.getFont(FontFactory.TIMES_ROMAN, 
          14, Font.NORMAL, new CMYKColor(75, 68, 67,90))); 
        
          Paragraph title8 = new Paragraph("Net Amount :" + jTextField9.getText()+" Rs", 
          FontFactory.getFont(FontFactory.TIMES_ROMAN, 
          14, Font.NORMAL, new CMYKColor(75, 68, 67,90))); 
          
          title6.setAlignment(Element.ALIGN_LEFT);
          document.add(title6);
          title7.setAlignment(Element.ALIGN_LEFT);
          document.add(title7);
          title8.setAlignment(Element.ALIGN_LEFT);
          document.add(title8);

      
            
            }    
        catch (DocumentException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                
                document.close();
                JOptionPane.showMessageDialog(null, "Report was successfully generated !", "Success !", JOptionPane.INFORMATION_MESSAGE);
                try {
                // TODO add your handling code here:
                jTextArea2.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
       try {

            char c = evt.getKeyChar();
            if(Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
       try {

            char c = evt.getKeyChar();
            if(Character.isDigit(c)||Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
       try {

            char c = evt.getKeyChar();
            if(!Character.isDigit(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
       try {

            char c = evt.getKeyChar();
            if(Character.isDigit(c)||Character.isAlphabetic(c))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        Brand = jComboBox2.getSelectedItem().toString();
        try{
                Connection c = DB.mycon();
                Statement s = c.createStatement();
                ResultSet rs2 = s.executeQuery("SELECT  Model FROM vehicletype where Brand = '"+Brand+"' ");
                while(rs2.next()){
                jComboBox3.addItem(rs2.getString("Model"));
                }
        }
        catch(Exception e){
            e.printStackTrace();
        }         
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
     int x = JOptionPane.showConfirmDialog(rootPane, "Do you really want to Log out ? ");
        if(x== 0){
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
